<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/16/016
 * Time: 11:11
 */
namespace me\gridVews;
use yii\grid\DataColumn;

class IdColumn extends DataColumn{
    //public $header='ID';
    public $attribute='id';
    //public $headerOptions;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}