<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/14/014
 * Time: 15:42
 */
namespace me\gridVews;
use yii\grid\GridView;
class TestColumn extends GridView{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }
}
